<!DOCTYPE html>
<html lang="fr">

<head>

    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Hell's Food</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="footer, contact, form, icons" />

    <!-- CSS Vendor -->

    <link href="https://fonts.googleapis.com/css?family=Great+Vibes|Montserrat|Playfair+Display" rel="stylesheet">
    <link href="http://fonts.googleapis.com/css?family=Cookie" rel="stylesheet" type="text/css">
    <script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
    <link rel="stylesheet" href="css/flexslider.css">


    <!-- CSS Perso -->

    <link rel="stylesheet" href="public/css/font-awesome.min.css">
    <link rel="stylesheet" href="public/css/normalize.css" />
    <link rel="stylesheet" href="public/css/style.css" />


</head>

<body>
    <?php require('apps/header.php'); ?>
    <?php require('apps/content.php'); ?>
    <?php require('apps/footer.php'); ?>
</body>

</html>
