<!DOCTYPE html>
<html lang="fr">

<head>

    <meta charset="utf-8" />
    <title>Hell's Food</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS Vendor -->

    <link href="https://fonts.googleapis.com/css?family=Great+Vibes|Montserrat|Playfair+Display" rel="stylesheet">
    <script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
    <link rel="stylesheet" href="css/flexslider.css">

    <!-- CSS Perso -->

    <link rel="stylesheet" href="public/css/font-awesome.min.css">
    <link rel="stylesheet" href="public/css/normalize.css" />
  <link rel="stylesheet" href="public/css/style.css" />
   <!-- <link rel="stylesheet" href="public/css/stylesamira.css" />-->


</head>

<body>
    <?php require('apps/header.php'); ?>
    <?php require('apps/home.php'); ?>
    <?php require('apps/footer.php'); ?>
</body>

</html>
