<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Appel CSS -->
    <link rel="stylesheet" href="public/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bree+Serif">
    <link rel="stylesheet" href="public/css/normalize.css">
    <link rel="stylesheet" type="text/css" href=" https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">

    <link rel="stylesheet" href="public/css/style.css">
    <title>Hell's Food</title>
</head>

<body>


    <?php require('apps/header.php'); ?>

    <?php require('apps/content.php'); ?>

    <?php require('apps/footer.php'); ?>
</body>

</html>