<section class="carte">
	<section>
		<h1>Entrée</h1>
		<ul>
			<li>
				<img src="public/image/1.jpg">
				<h3>11111</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,</p>
				<p>5€</p>
			</li>
			<li>
				<img src="public/image/2.jpg">
				<h3>11111</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,</p>
				<p>5€</p>
			</li>
			<li>
				<img src="public/image/1.jpg">
				<h3>11111</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,</p>
				<p>5€</p>
			</li>
		</ul>
	</section>	
		
	<section>
		<h1>plat</h1>
		<ul>
			<li>
				<img src="public/image/1.jpg">
				<h3>Blancs de poulet laqués au miel et sésame </h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,</p>
				<p>12€</p>
			</li>
			<li>
				<img src="public/image/2.jpg">
				<h3>Risotto aux cèpes et à l'orange</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,</p>
				<p>5€</p>
			</li>
			<li>
				<img src="public/image/3.jpg">
				<h3>Couscous végétarien sucré-salé</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,</p>
				<p>5€</p>
			</li>
		</ul>
	</section>	
	<section>
		<h1>Dessert</h1>
		<ul>
			<li>
				<img src="public/image/1.jpg">
				<h3>11111</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,</p>
				<p>5€</p>
			</li>
			<li>
				<img src="public/image/1.jpg">
				<h3>11111</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,</p>
				<p>5€</p>
			</li>
			<li>
				<img src="public/image/1.jpg">
				<h3>11111</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,</p>
				<p>5€</p>
			</li>
		</ul>
	</section>	
	<section>
		<h1>Boisson</h1>
		<ul>
			<li>
				<img src="">
				<h3>Blancs de poulet laqués au miel et sésame </h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,</p>
				<p>12€</p>
			</li>
		</ul>
	</section>	



</section>