<section class="carte">
    <section>
        <h1>Nos <span>Entrées</span></h1>
        <ul>
            <?php require('apps/display_entree.php'); ?>
        </ul>
    </section>

    <section>
        <h1>Nos <span>Plats</span></h1>
        <ul>
            <?php require('apps/display_plat.php'); ?>

        </ul>
    </section>
    <section>
        <h1>Nos <span>Desserts</span></h1>
        <ul>
            <?php require('apps/display_dessert.php'); ?>
        </ul>
    </section>

</section>