<form method="POST">
    <input type="hidden" name="action" value="create">
    <label for="comment">Commentaire:</label>
    <textarea type="text" id="description" name="content"></textarea>
    <label for="Name">name</label>
    <input type="text" name="name" placeholder="name">
    <label for="email">Email</label>
    <input type="text" name="email" placeholder="email">
    <div><input type="submit" value="Valider"></div>
</form>    


