 <?php require('apps/display_comments.php'); ?>
   <section class="comment">

    <form method="POST">
    		<h1>LAISSER UN COMMENTAIRE </h1>
    <input type="hidden" name="action" value="create">
    <label for="comment">Commentaire:</label>
    <textarea type="text" id="comment" name="content"></textarea>
    <label for="Name">Nom</label>
    <input type="text" name="name" placeholder="name">
    <label for="email">Email*</label>
    <input type="text" name="email" placeholder="email">
    <div><input type="submit" value="ENVOYER"></div>
    <div class="note"><P>* Votre adresse e-mail ne sera pas publié.</P></div>   
    
</form> 

</section>  


