<main>

    <section class="contact">
        <article>
            <img src="cuisiniere.gif" alt="">
        </article>
        <article>
            <h4>Nous contactez :</h4>
            <p>tel : 03.03.03.03.03 </p>
            <p>tel : 07.07.07.07.07</p>
            <h4>Adresse :</h4>

            <p>3 rue du meilleur restaurant </p>
            <p>99 999 Pays des Merveilles</p>
        </article>
    </section>
</main>

<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d10557.156411385244!2d7.7407191!3d48.5851631!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x2fa3aaa781002bd3!2s3W+Academy!5e0!3m2!1sfr!2sfr!4v1520411330250" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>