<form action="" method="post">

<strong><h1> Contactez-nous !</h1></strong>

    <div>
        <strong><label for="nom">Name :</label></strong>
        <input type="text" id="nom" />
    </div>
    <br>
    <div>
        <strong><label for="courriel">Courriel :</label></strong>
        <input type="email" id="courriel" />
    </div>
    <br>
    <div>
        <strong><label for="message">Message :</label></strong>
        <textarea id="message"></textarea>
    </div>
    <input type="reset" value="Effacer" /> <input type="submit" value="Envoyer" />
</form>
