<form id="formulaire de livraison">
  <fieldset>
    <legend>Coordonnées</legend>
    <ol>
      <li>
        <label for="nom">Nom</label>
        <input id="nom" name="nom" type="text" placeholder="Nom et prénom">
      </li>
      <li>
        <label for="email">Email</label>
        <input id="email" name="email" type="email" placeholder="exemple@domaine.fr">
      </li>
      <li>
        <label for="telephone">Téléphone</label>
        <input id="telephone" name="telephone" type="tel" placeholder="0674215498">
      </li>
    </ol>
  </fieldset>

  <fieldset>
    <legend>Adresse de livraison</legend>
      <ol>
        <li>
          <label for="numerorue">Numéro et Rue</label>
          <textarea id="numerorue" name="numerorue" rows="4"></textarea>
        </li>
        <li>
          <label for="codepostal">Code postal</label>
          <input id="codepostal" name="codepostal" type="text">
        </li>
          <li>
          <label for="ville">Ville</label>
          <input id="ville" name="ville" type="text">
        </li>
      </ol>
    </fieldset>
  
  <input type="submit" value="Envoyer">
</form>
