<section class="choices">
<h2>Merci de cocher ce que vous souhaitez commander ainsi que le nombre de portions :</h2>
<br>
<br>
<div><input type="checkbox" name= "choix1" value="choix1" >Foie gras<input type="number" name="howmuch" min="0">
</div>  
<div><input type="checkbox" name= "choix2" value="choix2" >Salade César<input type="number" name="howmuch" min="0">
</div>  
<div><input type="checkbox" name= "choix3" value="choix3" >Saumon fumé<input type="number" name="howmuch" min="0">
</div>  
<div><input type="checkbox" name= "choix4" value="choix4" >Homard breton<input type="number" name="howmuch" min="0">
</div>  
<div><input type="checkbox" name= "choix5" value="choix5" >Côte de veau<input type="number" name="howmuch" min="0">
</div>  
<div><input type="checkbox" name= "choix6" value="choix6" >Langoustines<input type="number" name="howmuch" min="0">
</div>
</section> 