<form method="POST">
<input type="hidden" name="action" value="step2">  
  <fieldset>
    <legend>Coordonnées</legend>
    <ol>
      <li>
        <label for="name">Name</label>
        <input id="name" name="name" type="text" placeholder="Nom et prénom">
      </li>
      <li>
        <label for="email">Email</label>
        <input id="email" name="email" type="email" placeholder="exemple@domaine.fr">
      </li>
      <li>
        <label for="phone">Téléphone</label>
        <input id="phone" name="phone" type="tel" placeholder="0674215498">
      </li>
    </ol>
  </fieldset>

  <fieldset>
    <legend>Adresse de livraison</legend>
      <ol>
        <li>
          <label for="address">Numéro et Rue</label>
          <textarea id="address" name="address" rows="4"></textarea>
        </li>
        <li>
          <label for="postcode">Code postal</label>
          <input id="postcode" name="postcode" type="text">
        </li>
          <li>
          <label for="city">Ville</label>
          <input id="city" name="city" type="text">
        </li>
          <li>
          <label for="date">Date</label>
          <input id="date" name="date" type="date">
        </li>
          <li>
          <label for="hours">Heure</label>
          <input id="hours" name="hours" type="time">
        </li>
          <li>
          <label for="comment">Commentaire</label>
          <input id="comment" name="comment" type="text">
        </li>
      </ol>
    </fieldset>
  
  <input type="submit" value="Envoyer">
</form>
