<form id="formulaire de livraison">
  <fieldset>
    <legend>Coordonnées</legend>
    <ol>
      <li>
        <label for="nom">Nom</label>
        <input id="nom" name="nom" type="text" placeholder="Nom et prénom">
      </li>
      <li>
        <label for="email">Email</label>
        <input id="email" name="email" type="email" placeholder="exemple@domaine.fr">
      </li>
      <li>
        <label for="telephone">Téléphone</label>
        <input id="telephone" name="telephone" type="tel" placeholder="0674215498">
      </li>
    </ol>
  </fieldset>

  <fieldset>
    <legend>Adresse de livraison</legend>
      <ol>
        <li>
          <label for="numerorue">Numéro et Rue</label>
          <textarea id="numerorue" name="numerorue" rows="4"></textarea>
        </li>
        <li>
          <label for="codepostal">Code postal</label>
          <input id="codepostal" name="codepostal" type="text">
        </li>
          <li>
          <label for="ville">Ville</label>
          <input id="ville" name="ville" type="text">
        </li>
      </ol>
    </fieldset>
  <button type="submit">Envoyer</button>
</form>

Commandez ce que vous souhaitez:<br>
<INPUT TYPE="checkbox" NAME= "plat1" VALUE="entrée1" >assiette scandinave<br>
<INPUT TYPE="checkbox" NAME= "plat2" VALUE="entrée2" CHECKED> charcuterie<br>
<INPUT TYPE="checkbox" NAME= "plat3" VALUE="plat1">aile de raie<br>
<INPUT TYPE="checkbox" NAME= "plat4" VALUE="plat2">gigot d'agneau<br>
<INPUT TYPE="checkbox" NAME= "plat5" VALUE="fromage" CHECKED> fromage<br>
<INPUT TYPE="checkbox" NAME= "plat6" VALUE="dessert">dessert maison