<section class="listereservation">
	 <ul>
	 	<li>
	      <h2>Nom   :  <?=($booking->getName())?></h2>
	      <h2>Date :  <?=($booking->getDate())?></h2>
	      <h2>Heure :  <?=($booking->getHours())?></h2>
	      <h2>Nombre de personne :  <?=($booking->getNumber())?></h2>
	      <h2>Commentaire :  <?=($booking->getcomment())?></h2>
	      <h2>Numero de téléphone :  <?=($booking->getPhone())?></h2>
        </li>
	 </ul>
	 <hr>
</section>
