<footer>
   Abonnez-vous à notre newsletter ! 
    <div class="newsletter">
        <form action="" ethod="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" target="_blank" class="input-group">
            <input type="email" value="" placeholder="email@example.com" name="EMAIL" id="mail" class="input-group-field hint" aria-label="email@example.com" autocorrect="off" autocapitalize="off">
            <span class="input-group-btn">
            <input type="submit" class="btn" name="subscribe" id="subscribe" value="Subscribe">
            </span>
        </form>
    </div>
    All rights reserved © 2018 RJBS
    
    <div>
        <nav>
            <a href="https://www.facebook.com/"><i class="fab fa-facebook" style="color:#363636"></i></a>
            <a href="https://twitter.com/"><i class="fab fa-twitter-square" style="color:#363636"></i></a>
            <a href="https://www.instagram.com/"><i class="fab fa-instagram" style="color:#363636"></i></a>
        </nav>
    </div>

</footer>
