<footer>
        
                        All rights reserved © 2018 RJBS

    <div>
        <nav>
            <a href="https://www.facebook.com/"><i class="fab fa-facebook" style="color:#363636"></i></a>
            <a href="https://twitter.com/"><i class="fab fa-twitter-square" style="color:#363636"></i></a>
            <a href="https://www.instagram.com/"><i class="fab fa-instagram" style="color:#363636"></i></a>
        </nav>
    </div>

    <section>
        <form method="POST">
            <input type="hidden" name="action" value="login"> email : <input type="text" name="email"> Password : <input type="password" name="password">
            <br>
            <input type="submit" value="login">
        </form>

    </section>

</footer>
