<footer class="footer-distributed">
    <div class="footer-left">

        <h3>Hell's<span>Food</span></h3>

        <p class="footer-links">
            <a href="#">Home</a> ·
            <a href="#">Menu</a> ·
            <a href="#">Booking</a> ·
            <a href="#">Delivery</a> ·
            <a href="#">Contact</a>
        </p>

        <p class="footer-company-name">RJBS &copy; 2018</p>

       <div class="footer-icons">

            <a href="#"><i class="fab fa-facebook"></i></a>
            <a href="#"><i class="fab fa-twitter-square"></i></a>
            <a href="#"><i class="fab fa-instagram"></i></a>
            

        </div>

    </div>

    <div class="footer-right">
        
   

        

        <form action="#" method="post">
            <input type="hidden" name="action" value="logout">
            
            <button>déconnexion</button>
            <!---<input type="submit" value="logout">
                  <textarea name="message" placeholder="Message"></textarea>--->


        </form>

    </div>
</footer>