<header>
    <div id="logo">Hell's Food </div>
    <nav>
        <a href="http://localhost/Projet-RJBS/index.php?page=home">HOME</a>
       <a href="http://localhost/Projet-RJBS/index.php?page=carte">MENU</a>
        <a href="http://localhost/Projet-RJBS/index.php?page=delivery">DELIVERY</a>
        <a href="http://localhost/Projet-RJBS/index.php?page=booking">BOOKING</a>
        <a href="http://localhost/Projet-RJBS/index.php?page=createfnb">CREATE</a>
    </nav>


</header>
