<header class="header-distributed">
    <h3>Hell's<span>Food</span></h3>
    <nav>
        <a href="http://localhost/Projet-RJBS/index.php?page=home">HOME</a>
        <a href="http://localhost/Projet-RJBS/index.php?page=carte">MENU</a>
        <a href="http://localhost/Projet-RJBS/index.php?page=booking">BOOKING</a>
        <a href="http://localhost/Projet-RJBS/index.php?page=delivery">DELIVERY</a>
         <a href="http://localhost/Projet-RJBS/index.php?page=contact">CONTACT</a>
    </nav>
 
</header>

