<main>
    <section class="home">
      
       <img src="souris.gif" alt="toto" style="float:left; width:35%">
        <article>
        Soyez le bienvenu, 
        <p>Lorem ipsum dolor <b> <span>Régis, Jallal, Brice et Samira</span> </b> sit amet, consectetur pisicing elit. Nesciunt omnis earum, amet, mollitia nobis magnam excepturi harum minus in, quis voluptas, reiciendis quam molestiae labore at fuga ipsam natus. Expedita. </p>
        
        <p>Lorem ipsum dolor sit amet, consectetur pisicing <span>Rue du meilleur des Restaurants </span> elit. Nesciunt omnis earum, amet,  mollitia nobis magnam excepturi harum minus in, quis voluptas, reiciendis quam molestiae labore at fuga ipsam natus. Expedita.Lorem ipsum dolor sit amet, consectetur pisicing elit. Nesciunt omnis earum, amet, mollitia nobis magnam excepturi harum minus in, quis voluptas, reiciendis quam molestiae labore at fuga ipsam natus. Expedita. </p>
        
        <p>Lorem ipsum dolor sit amet, consectetur pisicing elit. Nesciunt omnis earum, amet, mollitia nobis magnam excepturi harum minus in, quis voluptas, reiciendis quam molestiae labore at fuga ipsam natus. Expedita. <span>Au Pays des Merveilles</span> Lorem ipsum dolor sit amet, consectetur pisicing elit. Nesciunt omnis earum, amet, mollitia nobis magnam excepturi harum minus in, quis voluptas, reiciendis quam molestiae labore at fuga ipsam natus. Expedita. </p>
        
        <p>Lorem ipsum dolor sit amet, consectetur pisicing elit. Nesciunt omnis earum, amet, mollitia nobis magnam excepturi harum minus in, quis voluptas, </p>
        
        <p>Lorem ipsum dolor sit amet, consectetur pisicing elit. Nesciunt omnis earum, amet, mollitia nobis magnam excepturi harum minus in, quis voluptas, </p>
        
           <span>Bon appétit !</span>

        </article>
        
            
       
    </section>
</main>
