
<p>
Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi sequi praesentium sit officiis distinctio neque minima, earum deleniti ducimus atque accusamus nostrum error at blanditiis asperiores provident odio, dolor ipsam.</p>


<main>
   

    <section>

        <article class="presentation">
            <img src="/Projet-RJBS/public/img/background.jpg" alt="">

        </article>
    </section>

</main>

